name: build
on: [push, pull_request]

jobs:
    build:
      strategy:
        fail-fast: false
        matrix:
          os: [ ubuntu-latest, macos-13, windows-latest ]
          python-version: [ "3.8", "3.9", "3.10", "3.11", "3.12" ]
          include:
            - os: ubuntu-latest
              os-name: Linux
              pip-cache-path: ~/.cache/pip
            - os: macos-latest
              os-name: MacOS
              pip-cache-path: ~/Library/Caches/pip
            - os: windows-latest
              os-name: Windows
              pip-cache-path: ~\AppData\Local\pip\Cache
      name: 🛠️ Build py${{ matrix.python-version }} @ ${{ matrix.os-name }}
      runs-on: ${{ matrix.os }}

      steps:
        - name: Checkout code
          uses: actions/checkout@v4
        - name: Set up Python
          uses: actions/setup-python@v4
          with:
            python-version: ${{ matrix.python-version }}
        - name: Install pypa/build
          run: python -m pip install build --user --upgrade --progress-bar off
        - name: Building
          run: python -m build
        - name: Store distribution
          uses: actions/upload-artifact@v3
          with:
            name: python-package-distributions
            path: dist/
